language: node_js

dist: trusty

branches:
  except:
    - /^v[0-9]/

node_js:
  - "8"
  - "10"

before_install: npm i -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script: npm test

after_script: greenkeeper-lockfile-upload
